In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys
sys.path.append("../../")

In [4]:
from torchganime.data.dataset.video import SceneDataset
from torchganime.data.dataloader.video import VideoData
from pytorchvideo.transforms import Permute, Normalize
from torchvision import transforms

/usr/local/lib/python3.9/dist-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(


In [5]:
vd = SceneDataset(
    ["../../data/snk/raw_videos/01.mkv"], 
    transform=transforms.Compose([
        Permute((3, 0, 1, 2)), 
        transforms.Resize((128, 256))
        # Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
        ]
        ),
    recursive=True, 
    show_progress=True,
    min_max_len=(15, 25),
    detector="content", 
    threshold=15, 
    min_scene_len=15, 
    )

2022-12-28 14:27:43.079 | INFO     | torchganime.data.dataset.video:_get_video_paths:365 - Found 1 videos


In [6]:
vd[0].shape

torch.Size([3, 15, 128, 256])

In [5]:
dataloader = VideoData("../../data/snk/raw_videos/01.mkv", "../../data/snk/raw_videos/02.mkv", image_size=(128, 256), batch_size=8, num_workers=16)

2022-12-30 11:39:00.918 | INFO     | torchganime.data.dataset.video:_get_video_paths:365 - Found 1 videos
2022-12-30 11:39:01.024 | INFO     | torchganime.data.dataset.video:_get_video_paths:365 - Found 1 videos


In [23]:
i = 0
for b in dataloader.train_dataloader():
    print(b["frame_number"])
    print(b["first_frame"].shape)
    print(b["end_frame"].shape)
    print(b["target"].shape)
    target = b["target"]
    i += 1
    if i > 50:
        break

tensor([24, 17, 20, 19, 20, 19, 20, 23])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([20, 22, 24, 20, 19, 16, 20, 18])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([17, 22, 18, 18, 17, 18, 24, 19])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([16, 15, 17, 24, 15, 22, 20, 17])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([21, 16, 24, 24, 20, 15, 17, 15])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([20, 16, 24, 20, 15, 24, 24, 16])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([18, 18, 18, 20, 15, 24, 20, 16])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 128, 256])
torch.Size([8, 3, 24, 128, 256])
tensor([17, 21, 16, 16, 15, 15, 19, 24])
torch.Size([8, 3, 128, 256])
torch.